services:
  remote_ocr:
    build:
      context: .
      dockerfile: services/remote_ocr/Dockerfile
    command: uvicorn services.remote_ocr.server.main:app --host 0.0.0.0 --port 8081 --reload
    volumes:
      - ./:/workspace
    env_file:
      - .env
    ports:
      - "8081:8081"


